// Fictional sample content for the interface. Not live events or real reporting.
const demoSource = 'Trendz Global Desk · Demo';
export const demoStories = [
  {id:'d01',category:'Climate',region:'Africa',location:'Accra, Ghana',source:demoSource,publishedAt:'2026-10-05T11:40:00Z',title:'Coastal cities trial a shared early-warning network',summary:'A fictional pilot links community weather stations across three West African coastal cities, giving local responders more time to prepare for seasonal flooding.',whyItMatters:'Local alerts can help communities act sooner. The demo story explores how shared climate data could support that work.',imageClass:'thumb-ocean',imageLabel:'COASTAL RESILIENCE',topics:['Climate adaptation','West Africa','Early warnings']},
  {id:'d02',category:'Business',region:'Africa',location:'Nairobi, Kenya',source:demoSource,publishedAt:'2026-10-05T11:25:00Z',title:'Regional payments network expands its small-business pilot',summary:'In this illustrative scenario, a cross-border payments pilot adds new merchant partners in East Africa and tests lower-cost settlement for small exporters.',whyItMatters:'Smoother regional payments could make it easier for small firms to trade across borders.',imageClass:'thumb-tech',imageLabel:'TRADE & INNOVATION',topics:['Digital payments','Small business','Africa trade']},
  {id:'d03',category:'Ghana',region:'Africa',location:'Kumasi, Ghana',source:demoSource,publishedAt:'2026-10-05T11:12:00Z',title:'Kumasi makers test a new circular-economy hub',summary:'A sample community project brings repair workshops, material recovery and skills training together in one shared neighborhood space.',whyItMatters:'Reuse and repair initiatives can create new local livelihoods while reducing pressure on waste systems.',imageClass:'thumb-leaf',imageLabel:'LOCAL SOLUTIONS',imageUrl:'https://images.unsplash.com/photo-1776153380872-108ba14dc63d?auto=format&fit=crop&w=900&q=82',imageAlt:'Marketplace stalls and umbrellas in Kumasi, Ghana',imageCredit:'Wietse Jongsma · Unsplash',imageCreditUrl:'https://unsplash.com/photos/bustling-marketplace-with-crowded-stalls-and-buildings-w-jFW9XkDBg',imageIsIllustrative:true,topics:['Circular economy','Ghana','Community']},
  {id:'d04',category:'Technology',region:'Asia Pacific',location:'Singapore',source:demoSource,publishedAt:'2026-10-05T10:52:00Z',title:'A regional AI safety compact puts transparency first',summary:'This fictional policy briefing imagines technology teams and researchers agreeing to publish clearer evaluation summaries for high-impact AI systems.',whyItMatters:'Public evaluation summaries could help institutions compare systems and ask better questions before adoption.',imageClass:'thumb-tech',imageLabel:'AI & SOCIETY',topics:['AI governance','Transparency','Technology']},
  {id:'d05',category:'Science',region:'Europe',location:'Geneva, Switzerland',source:demoSource,publishedAt:'2026-10-05T10:30:00Z',title:'Open research teams map freshwater stress indicators',summary:'In a demo research scenario, universities combine satellite observations and field measurements to make watershed data easier to compare.',whyItMatters:'More accessible environmental data can help researchers and public agencies spot long-term changes.',imageClass:'thumb-sky',imageLabel:'OPEN SCIENCE',topics:['Water research','Open data','Climate science']},
  {id:'d06',category:'World',region:'Middle East',location:'Amman, Jordan',source:demoSource,publishedAt:'2026-10-05T10:08:00Z',title:'Community kitchens coordinate a citywide food-share week',summary:'A fictional network of neighborhood kitchens, growers and volunteers pilots a common schedule for redistributing surplus food.',whyItMatters:'Coordination can connect more people to existing community resources and reduce avoidable food waste.',imageClass:'thumb-food',imageLabel:'COMMUNITY NETWORKS',topics:['Food access','Community','Middle East']},
  {id:'d07',category:'Politics',region:'Americas',location:'Montevideo, Uruguay',source:demoSource,publishedAt:'2026-10-05T09:49:00Z',title:'Cities share a new public guide to participatory budgeting',summary:'A sample civic initiative packages lessons from neighborhood budget forums into a practical, openly available guide for municipal teams.',whyItMatters:'Clearer processes can make it easier for residents to see how local priorities become public projects.',imageClass:'thumb-city',imageLabel:'CIVIC LIFE',topics:['Local democracy','Public finance','Americas']},
  {id:'d08',category:'Entertainment',region:'Europe',location:'Lisbon, Portugal',source:demoSource,publishedAt:'2026-10-05T09:21:00Z',title:'Independent film collectives launch a shared screening circuit',summary:'In this illustrative arts story, small venues across several cities coordinate a traveling program of short films and filmmaker conversations.',whyItMatters:'Shared programming can help independent work find audiences beyond its home city.',imageClass:'thumb-culture',imageLabel:'CULTURE & IDEAS',topics:['Independent film','Arts','Culture']},
  {id:'d09',category:'Africa',region:'Africa',location:'Dakar, Senegal',source:demoSource,publishedAt:'2026-10-05T08:58:00Z',title:'Youth athletics clubs build a cross-border coaching exchange',summary:'A fictional sports federation pilot pairs local coaches for a season of training visits, shared resources and youth meets.',whyItMatters:'Practical exchanges can open more pathways for young athletes and the coaches who support them.',imageClass:'thumb-ball',imageLabel:'SPORT & COMMUNITY',topics:['Youth sport','Coaching','West Africa']},
  {id:'d10',category:'Health',region:'Asia Pacific',location:'Manila, Philippines',source:demoSource,publishedAt:'2026-10-05T08:32:00Z',title:'Mobile clinics test a simpler follow-up care pathway',summary:'This demo public-health scenario looks at how neighborhood clinics could coordinate follow-up visits with local health teams using shared appointment tools.',whyItMatters:'More reliable follow-up may help patients stay connected to routine care between clinic visits.',imageClass:'thumb-health',imageLabel:'PUBLIC HEALTH',topics:['Primary care','Health access','Asia Pacific']},
  {id:'d11',category:'World',region:'Middle East',location:'Muscat, Oman',source:demoSource,publishedAt:'2026-10-05T08:11:00Z',title:'Ports experiment with a common standard for cleaner shipping',summary:'A fictional industry working group begins a pilot to report port-call emissions using a consistent, openly documented template.',whyItMatters:'Comparable reporting could help ports and operators understand where lower-emission changes have the most impact.',imageClass:'thumb-ocean',imageLabel:'GLOBAL COMMERCE',imageUrl:'https://images.unsplash.com/photo-1784910627780-e49fa3a365fb?auto=format&fit=crop&w=900&q=82',imageAlt:'Cargo boat and cranes at the Port of Rotterdam',imageCredit:'Julia Taubitz · Unsplash',imageCreditUrl:'https://unsplash.com/photos/boat-on-water-with-a-distant-port-and-cranes-eKuNz_JJLJs',imageIsIllustrative:true,topics:['Shipping','Clean energy','Climate']},
  {id:'d12',category:'Sports',region:'Americas',location:'Montevideo, Uruguay',source:demoSource,publishedAt:'2026-10-05T07:48:00Z',title:'Public parks open weekend spaces for neighborhood sports',summary:'In this fictional local update, a city recreation program coordinates volunteer coaches and open practice sessions across several public parks.',whyItMatters:'Accessible neighborhood activities can make it easier for families to take part in local sport.',imageClass:'thumb-ball',imageLabel:'SPORT & COMMUNITY',topics:['Youth sport','Community','Americas']},
];
